data:
  train_data_path : '/Users/jatinprakash/Desktop/val2017'
  train_annotate_path : '/Users/jatinprakash/Desktop/annotations/instances_val2017.json'
  val_data_path : '/Users/jatinprakash/Desktop/val2017'
  val_annotate_path : '/Users/jatinprakash/Desktop/annotations/instances_val2017.json'

train:
  batch_size: 4
  num_workers: 4
  lr: 1e-3
  momentum: 0.9
  weight_decay: 0.001
  step_size: 10
  gamma: 0.1

  alpha: 1.0
  exp_name : 'COCO-train'
  model_save_path: '/Users/jatinprakash/Desktop/val2017'
